networks:
  default:
    name: bully_network
    external: true

services:
  openclaw-gateway:
    environment:
      # TZ: ${OPENCLAW_TZ:-UTC}
      ## KEYS
      ROUTER_API_KEY: ${ROUTER_API_KEY}
      OPENCLAW_GATEWAY_PASSWORD: ${OPENCLAW_GATEWAY_PASSWORD}
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN:-}
      ## Discord Keys
      OPENCLAW_DISCORD_TOKEN: ${OPENCLAW_DISCORD_TOKEN:-}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_CUSTODIAN_TOKEN}
      USER_DISCORD_ID:
      DISCORD_CHANNEL_GENERAL: ${DISCORD_CHANNEL_GENERAL}
      DISCORD_CHANNEL_COMMS: ${DISCORD_CHANNEL_COMMS}
      DISCORD_CHANNEL_PM: ${DISCORD_CHANNEL_PM}
      DISCORD_CHANNEL_ADMIN: ${DISCORD_CHANNEL_ADMIN}
      DISCORD_CHANNEL_CODE: ${DISCORD_CHANNEL_CODE}
      DISCORD_USER_ID_PM: ${DISCORD_USER_ID_PM}
      DISCORD_BOT_PM_TOKEN: ${DISCORD_BOT_PM_TOKEN}
      DISCORD_USER_ID_ARCHITECT: ${DISCORD_USER_ID_ARCHITECT}
      DISCORD_BOT_ARCHITECT_TOKEN: ${DISCORD_BOT_ARCHITECT_TOKEN}
      DISCORD_USER_ID_ADMIN: ${DISCORD_USER_ID_ADMIN}
      DISCORD_BOT_ADMIN_TOKEN: ${DISCORD_BOT_ADMIN_TOKEN}




      # Messy stuff I probably don't use
      OPENCLAW_ALLOW_INSECURE_PRIVATE_WS: ${OPENCLAW_ALLOW_INSECURE_PRIVATE_WS:-}
      OPENCLAW_DISABLE_BONJOUR: ${OPENCLAW_DISABLE_BONJOUR:-}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-}
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:-}
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: ${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:-}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL:-http/protobuf}
      OTEL_SERVICE_NAME: ${OTEL_SERVICE_NAME:-}
      OTEL_SEMCONV_STABILITY_OPT_IN: ${OTEL_SEMCONV_STABILITY_OPT_IN:-}
      OPENCLAW_OTEL_PRELOADED: ${OPENCLAW_OTEL_PRELOADED:-}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY:-}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY:-}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE:-}