services:
  default-service:
    restart: unless-stopped
    env_file:
      - ../.config/.env #uses system-wide variables as-needed
      - .env
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
      - NET_ADMIN

  media-service:
    extends:
      service: default-service
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - "987"  # render
      - "983"  # video

  agent-service:
    extends:
      service: media-service
    volumes:
      - "${DATA_OUTSIDE}:/data:rw"
      - "${WIKI_OUTSIDE}:/data/wiki:rw"
      - "${PROD_OUTSIDE}:/data/production:ro"
      - "${VAULT_OUTSIDE}:/data/vault:ro"

  browser-service:
    image: lscr.io/linuxserver/chromium:latest
    extends:
      service: media-service
    security_opt:
      - seccomp=unconfined
    environment:
      - CUSTOM_USER_AGENT=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
      - TITLE=Browser Control
      - CHROME_CLI=--remote-debugging-port=9222 --remote-debugging-address=127.0.0.1 --disable-blink-features=AutomationControlled
    volumes:
      - "./config/selkies/chromium-config:/config/.config/labwc"
