# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json
logLevel: debug
logToStdout: "both"
healthCheckTimeout: 120

models:
  "Gemma4-E4B":
    cmd: |
      llama-server
      --host 0.0.0.0
      --port ${PORT}
      --model /models/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive-IQ4_XS.gguf
      --n-gpu-layers 99
      --threads 8
      --ctx-size 8192
